image: node:18-alpine

stages:
  - build
  - deploy

variables:
  # Cache node_modules between jobs
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - node_modules/

build:
  stage: build
  script:
    # Install dependencies if package.json exists
    - |
      if [ -f "package.json" ]; then
        npm ci --prefer-offline --cache .npm
        # Build the Slidev presentation with base path for GitLab Pages
        npm run build -- --base /pathways_to_learn_python_for_scientific_software_development/
      else
        echo "No package.json found, using existing dist directory"
      fi
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - master
    - main

pages:
  stage: deploy
  dependencies:
    - build
  script:
    # GitLab Pages expects files in 'public' directory
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - main
  tags:
    - site